### ISSUE TITLE
Suggestion: Disable the DELETE key shortcut when in the text window

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Nenotriple/img-txt_viewer#19]
When typing to edit the text, it's annoying that the DELETE key to remove the image/caption pair is still active, as DELETE is a common key used in text-editing to delete the next letter or word with CTRL + DEL.

**Comment by Nenotriple** [comment]
Thanks for the suggestion.

I could change the bind to "Shift + Delete", it's more simple than handling what's active, and it's still a quick single handed hotkey. Is that alright with you?

I have a big update coming soon with a bunch of new tools and changes so this will have to wait until that release.

If you're using the Python version you can easily edit or comment out line 433 of `img-txt_viewer.pyw` and disable this behavior, or change the binding to `'<Shift-Delete>'`.  (region -  CLASS ImgTxtViewer > Bindings)

**Comment by Nenotriple** [comment]
Sorry about the auto-save not being reliable for you, that sucks. I can't think of many situations where it would fail, but it may be important to point out that it only actually saves the file when moving between pairs or closing the app. There were some cases in the past where the file wasn't saving when the index "rolled over" like going from the last pair to the first pair, or from the first to last pair, but that should be solved now.

I was hesitant to make the save button bigger because I made some UI changes around it and thought it might look a bit too big, but I think it looks fine at double the height. I'll add that change in with the next release, I may make it something that's toggled on/off though.

I won't go into all the details of each tool or change because there's a lot to cover and it will be in the release notes, but here's the rundown:

New tools: Find Duplicate Files, Rename/convert img-txt Pairs, Expand Current Image, Crop Image, Flip Image, Rotate Image, Duplicate Pair.

I made some changes to Filter Pairs, and Resize Images to make them more useful.

Some bug fixes.

Some UI adjustments like replacing the directory button with a text entry, image info is displayed above the current image, and some other little things.


I'm pretty happy with the "Expand Image" tool. It's used to expand an image to a square aspect ratio without cropping. It does this by expanding the pixels from the "long edge" outward to fill the space required to make the image square, like this.


(From this 👇)
![014aa](https://github.com/Nenotriple/img-txt_viewer/assets/70049990/45b9fa0c-3046-4f02-890c-5416dfca9bb6)


(To this 👇)
![014aa_ex](https://github.com/Nenotriple/img-txt_viewer/assets/70049990/a3f62464-457e-4c94-997b-ffc543700cb1)


It's only intended to be used on images with simple or gradient backgrounds where the "content" of the image isn't cropped along the long side. This way the tool can cleanly expand the background.


But you might expect that it doesn't work for images where the background can't be expanded cleanly, like this:


(From this 👇)
![012 - Copy](https://github.com/Nenotriple/img-txt_viewer/assets/70049990/33aa9a4d-c03a-46b7-ae02-fa28a50dd8eb)


(To this 👇)
![012 - Copy_ex](https://github.com/Nenotriple/img-txt_viewer/assets/70049990/c44d5386-6969-461e-96aa-be6ca8150c8e)


> This is still my favorite tool for caption management out of all of them.

Thank you so much, it really means a ton. ❤️

**Comment by MNeMoNiCuZ** [comment]
Thanks for your fixes.

The new improvements sound fantastic and a great addition to the tool. I especially like the resizer.
I'll add a few wishlist items as a new topic. I don't want to derail this conversation.

**Comment by Nenotriple** [comment]
Ok I'll take a look.

I'm not making the code commits right now, but these suggestions have been committed locally and will be in the next release. I've made the save button height a toggle that can be been switched on/off by right clicking the save button, or from the "Options" menu.

**Comment by MNeMoNiCuZ** [comment]
Fantastic! Thanks for making it an option!
That's how development should be done :D
