### ISSUE TITLE
Feature request - restore previous state

### ISSUE THREAD

**Issue by younyokel** [Nenotriple/img-txt_viewer#21]
Useful feature when you accidentally close the app, and when you open it again, it restores the previous path and file from where I left off

**Comment by Nenotriple** [comment]
That sounds like a good suggestion.

<br>

Here's how I'll make work:

When closing the app, a `settings.cfg` file will be created with the `last_directory` and `last_index` values.

When launching the app, the settings file is read, and if the path is valid, you'll be asked if you want to reload the last directory.

<br>

It'd be pretty easy to add other settings, but for now, it just restores the directory and index. I'm making these changes locally, so this feature will be included in the next release.

Thanks!

**Comment by Nenotriple** [comment]
I've posted v1.90 with these changes.

because you requested something like this before, I also wanted to point out a couple of new features related to blank/empty text files

The `Filter Pairs` tool can now filter just empty text files.

You can now quickly jump to the next empty text file from Tools menu or by pressing `Ctrl+E`.

Hopefully you find those somewhat useful.
