### ISSUE TITLE
Image Grid suggestions - stay open, separate window, resizable

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [Nenotriple/img-txt_viewer#24]
Nice! That works really well!
My only recommendation is that the "Auto close"-option is off by default.
I don't think having it as true makes the most sense as a default behavior.
It's a bit annoying that this option is not saved, and it keeps defaulting to true.

Additionally, it would be nice to be able to maximize and resize the image grid. Aside from technical difficulties with implementation, I don't see a good reason to keep it this small and limited.

Additionally, it should probably be implemented as a proper window, instead of whatever it is now.

As it is, if I open something over it, like my web browser to type out these words, and then go back to the program, the Image Grid window does not show up. It's permanently hidden behind my web browser or other application overlapping it.

_Originally posted by @MNeMoNiCuZ in https://github.com/Nenotriple/img-txt_viewer/issues/20#issuecomment-2194321706_

**Comment by Nenotriple** [comment]
> Auto-close

I've added this variable to the "settings.cfg" file, and the default/fallback is now off. 

> Proper window

It is a little bit of an odd setup. I was able to fix the window focus. You should be able to get the focus of the image grid from the taskbar now.

> Resize window

I did limit resizing horizontally because I couldn't get the thumbnails to display nicely. There are still some issues with vertical spacing that I haven't been able to figure out, and I think they're related. Basically, I end up with some extra space or padding, and I don't really know where it's coming from. I'll keep looking into this, it shouldn't super difficult, I just really need to look at everything and do some tests.

I won't be at my desktop for a couple weeks, so v1.95 may be a long time away. I'll see if I can build the executable some other way.

**Comment by MNeMoNiCuZ** [comment]
No rush on my behalf! I'm not about to use it or need these features right now :)

So take your time and enjoy whatever you are about to!

**Comment by Nenotriple** [comment]
This is fixed in v1.95 6d8f859

- `Auto-Close`: Is now saved to the `settings.cfg` file.
- Fixed the issue of not being able to focus on the image grid window when selecting it from the taskbar.
